# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memegenerator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='memegenerator.proto',
    package='aimemes',
    syntax='proto3',
    serialized_options=b'\242\002\003HLW',
    serialized_pb=b'\n\x13memegenerator.proto\x12\x07\x61imemes\".\n\x0bMemeRequest\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\x12\x0e\n\x06memeid\x18\x02 \x01(\t\"\x18\n\tMemeReply\x12\x0b\n\x03url\x18\x01 \x01(\t2A\n\x05Memer\x12\x38\n\nGetMemeUrl\x12\x14.aimemes.MemeRequest\x1a\x12.aimemes.MemeReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3'
)


_MEMEREQUEST = _descriptor.Descriptor(
    name='MemeRequest',
    full_name='aimemes.MemeRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='caption', full_name='aimemes.MemeRequest.caption', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='memeid', full_name='aimemes.MemeRequest.memeid', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=78,
)


_MEMEREPLY = _descriptor.Descriptor(
    name='MemeReply',
    full_name='aimemes.MemeReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='url', full_name='aimemes.MemeReply.url', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=80,
    serialized_end=104,
)

DESCRIPTOR.message_types_by_name['MemeRequest'] = _MEMEREQUEST
DESCRIPTOR.message_types_by_name['MemeReply'] = _MEMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemeRequest = _reflection.GeneratedProtocolMessageType('MemeRequest', (_message.Message,), {
    'DESCRIPTOR': _MEMEREQUEST,
    '__module__': 'memegenerator_pb2'
    # @@protoc_insertion_point(class_scope:aimemes.MemeRequest)
})
_sym_db.RegisterMessage(MemeRequest)

MemeReply = _reflection.GeneratedProtocolMessageType('MemeReply', (_message.Message,), {
    'DESCRIPTOR': _MEMEREPLY,
    '__module__': 'memegenerator_pb2'
    # @@protoc_insertion_point(class_scope:aimemes.MemeReply)
})
_sym_db.RegisterMessage(MemeReply)


DESCRIPTOR._options = None

_MEMER = _descriptor.ServiceDescriptor(
    name='Memer',
    full_name='aimemes.Memer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=106,
    serialized_end=171,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetMemeUrl',
            full_name='aimemes.Memer.GetMemeUrl',
            index=0,
            containing_service=None,
            input_type=_MEMEREQUEST,
            output_type=_MEMEREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_MEMER)

DESCRIPTOR.services_by_name['Memer'] = _MEMER

# @@protoc_insertion_point(module_scope)
