# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x10helloworld.proto\x12\nhelloworld\"\x1e\n\x0bMemeRequest\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\"\x18\n\tMemeReply\x12\x0b\n\x03url\x18\x01 \x01(\t2I\n\x07Greeter\x12>\n\nGetMemeUrl\x12\x17.helloworld.MemeRequest\x1a\x15.helloworld.MemeReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_MEMEREQUEST = _descriptor.Descriptor(
  name='MemeRequest',
  full_name='helloworld.MemeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caption', full_name='helloworld.MemeRequest.caption', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_MEMEREPLY = _descriptor.Descriptor(
  name='MemeReply',
  full_name='helloworld.MemeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='helloworld.MemeReply.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['MemeRequest'] = _MEMEREQUEST
DESCRIPTOR.message_types_by_name['MemeReply'] = _MEMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemeRequest = _reflection.GeneratedProtocolMessageType('MemeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEMEREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.MemeRequest)
  })
_sym_db.RegisterMessage(MemeRequest)

MemeReply = _reflection.GeneratedProtocolMessageType('MemeReply', (_message.Message,), {
  'DESCRIPTOR' : _MEMEREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.MemeReply)
  })
_sym_db.RegisterMessage(MemeReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMemeUrl',
    full_name='helloworld.Greeter.GetMemeUrl',
    index=0,
    containing_service=None,
    input_type=_MEMEREQUEST,
    output_type=_MEMEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
