# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import memegenerator_pb2 as memegenerator__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMemeUrl = channel.unary_unary(
                '/aimemes.Greeter/GetMemeUrl',
                request_serializer=memegenerator__pb2.MemeRequest.SerializeToString,
                response_deserializer=memegenerator__pb2.MemeReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetMemeUrl(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMemeUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemeUrl,
                    request_deserializer=memegenerator__pb2.MemeRequest.FromString,
                    response_serializer=memegenerator__pb2.MemeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimemes.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetMemeUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimemes.Greeter/GetMemeUrl',
            memegenerator__pb2.MemeRequest.SerializeToString,
            memegenerator__pb2.MemeReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
