# Generated by Django 3.0.6 on 2020-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='templateid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='templatename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
