# Generated by Django 3.0.6 on 2020-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20200607_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='templateid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='templatename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
